export enum TaskAction {
  TASK_CREATED = 'TASK_CREATED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_DELETED = 'TASK_DELETED',
  ASSIGNEE_ADDED = 'ASSIGNEE_ADDED',
  ASSIGNEE_REMOVED = 'ASSIGNEE_REMOVED',
  STATUS_ADDED = 'STATUS_ADDED',
  STATUS_REMOVED = 'STATUS_REMOVED',
  CURRENT_STATUS_CHANGED = 'CURRENT_STATUS_CHANGED',
  LABEL_ADDED = 'LABEL_ADDED',
  LABEL_REMOVED = 'LABEL_REMOVED',
  TASK_CLONED = 'TASK_CLONED',
  COMMENT_ADDED = 'COMMENT_ADDED',
}

